backend:
  name: github
  repo: exorde-labs/exorde-landingpage
  branch: develop # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
- label: "Pages"
  name: "pages"
  files:
    - label: "Homepage"
      name: "home"
      file: "site/content/homepage.yml"
      fields:
        - {label: Title, name: title, widget: string}
        - {label: Intro, name: intro, widget: markdown}
        - label: Section
          name: section
          widget: list
          fields:
            - {label: Title, name: title, widget: string}
            - {label: Subtitle, name: subtitle, widget: string}
            - {label: Photo, name: photo, widget: image}