backend:
  name: github
  repo: exorde-labs/exorde-landingpage
  branch: develop # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
- label: "Pages"
  name: "pages"
  i18n:
      structure: single_file
      locales: [en, fr]
  files:
    - label: "Homepage"
      name: "home"
      file: "site/content/homepage.json"
      i18n: true
      fields:
        - label: SEO
          name: seo
          widget: object
          i18n: true
          collapsed: true
          fields:
            - {label: Title, name: title, widget: string, i18n: true}
            - {label: Description, name: description, widget: text, i18n: true}
            - {label: Image, name: image, widget: image, i18n: true}
        - {label: Title, name: title, widget: string, i18n: true}
        - {label: Intro, name: intro, widget: text, i18n: true}
        - label: News
          name: news
          widget: list
          i18n: true
          collapsed: true
          required: false
          fields:
            - {label: Title, name: title, widget: string}
            - {label: Credibility, name: credibility, widget: number}
            - {label: Image, name: image, widget: image}
        - label: Stats
          name: stats
          widget: list
          i18n: true
          collapsed: true
          required: false
          fields:
            - {label: Title, name: title, widget: string}
            - {label: Title color, name: title_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
            - {label: Title color (dark mode), name: title_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
            - {label: Number, name: number, widget: number}
            - {label: Number color, name: number_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
            - {label: Number color (dark mode), name: number_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
            - {label: Description, name: description, widget: text}
            - {label: Description color, name: description_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
            - {label: Description color (dark mode), name: description_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
        - label: Sections
          name: sections
          widget: list
          i18n: true
          collapsed: true
          required: false
          fields:
            - {label: Title, name: title, widget: string}
            - {label: Title color, name: title_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
            - {label: Title color (dark mode), name: title_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
            - {label: Keyword, name: keyword, widget: string}
            - {label: Keyword color, name: keyword_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
            - {label: Keyword color (dark mode), name: keyword_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
            - {label: Description, name: description, widget: text}
            - {label: Description color, name: description_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
            - {label: Description color (dark mode), name: description_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
            - {label: Background color, name: background_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
            - {label: Background color (dark mode), name: background_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
            - {label: Card alignment, name: align, widget: select, options: ["left", "alternate", "right"]}
            - label: Cards
              name: cards
              widget: list
              collapsed: true
              fields:
                - {label: Title, name: title, widget: string}
                - {label: Description, name: description, widget: markdown}
                - {label: Icon, name: icon, widget: image}
                - {label: Button Label, name: button_label, widget: string}
                - {label: Icon color, name: icon_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
                - {label: Icon color (dark mode), name: icon_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
                - {label: Title color, name: title_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
                - {label: Title color (dark mode), name: title_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
                - {label: Description color, name: description_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
                - {label: Description color (dark mode), name: description_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
                - {label: Button background color, name: button_background_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
                - {label: Button background color (dark mode), name: button_background_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
        - label: Use cases
          name: use_cases
          widget: object
          summary: Use cases section
          i18n: true
          collapsed: true
          fields:
            - {label: Title, name: title, widget: string, i18n: true}
            - {label: Title color, name: title_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
            - {label: Title color (dark mode), name: title_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
            - {label: Keyword, name: keyword, widget: string, i18n: true}
            - {label: Keyword color, name: keyword_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
            - {label: Keyword color (dark mode), name: keyword_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
            - {label: Description, name: description, widget: text, i18n: true}
            - {label: Description color, name: description_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
            - {label: Description color (dark mode), name: description_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
            - {label: Background color, name: background_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
            - {label: Background color (dark mode), name: background_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
- label: "Use cases"
  name: "use_cases"
  i18n: true
  folder: "site/use-cases"
  create: true
  fields:
    - label: SEO
      name: seo
      widget: object
      i18n: true
      collapsed: true
      fields:
        - {label: Title, name: title, widget: string, i18n: true}
        - {label: Description, name: description, widget: text, i18n: true}
    - {label: "Title", name: "title", widget: "string", i18n: true}
    - {label: "Publish Date", name: "date", widget: "datetime", i18n: duplicate}
    - {label: "Featured Image", name: "thumbnail", widget: "image", i18n: duplicate}
    - {label: "Body", name: "body", widget: "markdown", i18n: true}
    - {label: "Slug", name: "slug", widget: "string", i18n: duplicate}
- label: "Components"
  name: "components"
  i18n:
    structure: single_file
    locales: [en, fr]
  files:
    - label: "Navbar"
      name: "navbar"
      file: "site/content/components/navbar.json"
      i18n: true
      fields:
        - {label: Background color, name: background_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
        - {label: Background color (dark mode), name: background_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
        - {label: Text color, name: text_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
        - {label: Text color (dark mode), name: text_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name"}
    - label: "Footer"
      name: "footer"
      file: "site/content/components/footer.json"
      i18n: true
      fields:
        - {label: Logo, name: logo, widget: image, i18n: duplicate}
        - {label: background_color, name: background_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
        - {label: background_color_dark, name: background_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
        - {label: text_color, name: text_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
        - {label: text_color_dark, name: text_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
        - {label: category_color, name: category_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
        - {label: category_color_dark, name: category_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
        - label: Categories
          name: categories
          widget: list
          i18n: true
          fields:
            - {label: Title, name: title, widget: string, i18n: true}
            - label: Items
              name: items
              widget: list
              i18n: true
              fields:
                - {label: Label, name: label, widget: string, i18n: true}
                - {label: Link, name: link, widget: string, i18n: true}
                - {label: External, name: external, widget: boolean, i18n: duplicate}
        - {label: Copyright, name: copyright, widget: string, i18n: true }
        - label: Socials
          name: socials
          widget: list
          i18n: true
          fields:
            - {label: Id, name: id, widget: string, i18n: duplicate}
            - {label: Link, name: link, widget: string, i18n: true}
            - {label: Icon, name: icon, widget: image, i18n: duplicate}
            - {label: Icon color, name: icon_color, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
            - {label: Icon color (dark theme), name: icon_color_dark, widget: relation, collection: "style", search_fields: ["colors.*.name"], value_field: "colors.*.name", i18n: duplicate}
- label: "Style"
  name: "style"
  files:
    - label: Colors
      name: colors
      file: "site/style/colors.json"
      fields:
        - label: Colors
          name: colors
          widget: list
          fields:
            - {label: Name, name: name, widget: string}
        
